//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class InfluencePatternHolder
{
	private Vector2 relCoord; //Relative coordinate of tower, assuming facing up
	public Vector2 relCoordRotated;
	public float vpsInfluence; // Value Per second of influence.
	public float degRotation; //Degrees Rotated, will return the relative based on this value
	public InfluencePatternHolder (Vector2 relCoord,  float vpsInfluenceRate, float degreeRotation)
	{
		this.relCoord = relCoord;
		this.relCoordRotated =  Quaternion.Euler(0,0, -1*degreeRotation)* new Vector3(relCoord.x, relCoord.y,0);
		this.vpsInfluence = vpsInfluenceRate;
	}
	
	
}


