//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

/// <summary>
/// Mode.  Gameplay mode:  1 vs. 1, 2 vs, 2 4 player FFA?
/// 
/// </summary>
public enum Mode
{
	OneVOne,
	TwoVTwo,
	FourPFFA
}


